services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5050
      - MONGO_URI=mongodb://mongo:27017/expenses
    depends_on:
      - mongo
    ports:
      - "5050:5050"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo_data:
